import { MemoryStore } from '../memory/memory-store.js';
import { SkillManager } from './skill-manager.js';
import { ForkReviewAgent } from './fork-review-agent.js';
import { buildReviewSystemPrompt } from '../api/review-prompts.js';
import { AIProvider, ChatOptions } from '../api/provider.interface.js';
import { AgentResponse } from '../agents/agent-response-parser.js';
import fs from 'node:fs/promises';
import path from 'node:path';

async function main() {
  console.log('🧪 Starting End-to-End Verification for ForkReviewAgent & Learning Loop...');

  // 1. Verify Dynamic System Prompt Composition
  const memoryPrompt = buildReviewSystemPrompt({ reviewMemory: true, reviewSkills: false });
  const skillPrompt = buildReviewSystemPrompt({ reviewMemory: false, reviewSkills: true });
  const combinedPrompt = buildReviewSystemPrompt({ reviewMemory: true, reviewSkills: true, refineFocus: 'test refine focus' });

  if (!memoryPrompt.includes('USER.md') || !skillPrompt.includes('Read-Before-Write Handshake')) {
    throw new Error('Prompt composition check failed');
  }
  if (!combinedPrompt.includes('test refine focus')) {
    throw new Error('Refine focus injection failed');
  }
  console.log('✔ Review Prompts dynamic builder validated.');

  // 2. Mock Provider with chained actions
  let turn = 0;
  const mockProvider: AIProvider = {
    async streamChat(prompt: string, options: ChatOptions): Promise<AgentResponse> {
      turn++;
      if (turn === 1) {
        return {
          thought: 'Creating a test skill for learning loop',
          actions: [
            {
              type: 'skill_manage',
              action: 'create',
              name: 'test-learning-loop-skill',
              content: '---\nname: test-learning-loop-skill\ndescription: A test skill generated by learning loop\n---\n# Procedure\n1. Do this step.'
            },
            {
              type: 'memory',
              action: 'add',
              target: 'user',
              content: '- User preference: likes concise feedback'
            }
          ]
        };
      }
      return {
        thought: 'Completed review',
        actions: []
      };
    }
  };

  const testTempDir = path.join(process.cwd(), '.agents', 'skills', 'test-learning-loop-skill');
  try {
    await fs.rm(testTempDir, { recursive: true, force: true });
  } catch {}

  const memoryStore = new MemoryStore();
  const skillManager = new SkillManager();
  let notificationReceived = '';

  const agent = new ForkReviewAgent({
    memoryStore,
    skillManager,
    provider: mockProvider,
    onNotification: (msg) => {
      notificationReceived = msg;
    }
  });

  // 3. Counter test
  for (let i = 0; i < 10; i++) agent.onUserTurn();
  for (let i = 0; i < 10; i++) agent.onToolIteration();

  const history = [
    { role: 'user', content: 'Please configure my build script' },
    { role: 'assistant', content: 'I configured the build script with pnpm' }
  ];

  await agent.maybeTriggerReview(history);
  await agent.currentReviewPromise;

  if (agent.turnsSinceMemory !== 0 || agent.itersSinceSkill !== 0) {
    throw new Error('Counters were not reset after successful review');
  }

  console.log(`✔ Counters reset verified. Notification: "${notificationReceived}"`);

  // 4. Verify skill was actually created with created_by: 'agent'
  const usagePath = path.join(testTempDir, '.usage.json');
  const usageRaw = await fs.readFile(usagePath, 'utf-8');
  const usage = JSON.parse(usageRaw);

  if (usage.created_by !== 'agent') {
    throw new Error(`Expected created_by to be 'agent', got ${usage.created_by}`);
  }
  console.log('✔ Skill created with provenance created_by: agent verified.');

  // Clean up test skill
  await fs.rm(testTempDir, { recursive: true, force: true });

  console.log('🎉 End-to-End Verification completed successfully!');
}

main().catch(err => {
  console.error('❌ Verification failed:', err);
  process.exit(1);
});
